#!/bin/bash

# Collect command line arguments (positional metadata filename and optional device)
DEVICE="cpu"
while getopts ":d:" opt; do
    case $opt in
        d) DEVICE="$OPTARG" ;;
        \?) echo "Invalid option: -$opt"
            exit 1 ;;
    esac
done
shift $((OPTIND -1))
METADATA_TSV="$1"
OUTPUT_DIR="$2"
echo "Using device: $DEVICE"

# Load metadata tsv
if [[ ! -f "$METADATA_TSV" ]]; then
    echo "Metadata TSV not found: $METADATA_TSV" >&2
    exit 1
fi

# determine column indices from header (expects tab-separated header with
# columns: ref_wav, ref_text, target_text, path)
IFS=$'\n' read -r header < "$METADATA_TSV"
IFS=$'\t' read -ra hdr_cols <<< "$header"
idx_ref_wav=-1; idx_ref_text=-1; idx_target_text=-1; idx_path=-1
for i in "${!hdr_cols[@]}"; do
    case "${hdr_cols[$i]}" in
        ref_wav)       idx_ref_wav=$i ;;
        ref_text)      idx_ref_text=$i ;;
        target_text)   idx_target_text=$i ;;
        path)          idx_path=$i ;;
    esac
done
if (( idx_ref_wav < 0 || idx_ref_text < 0 || idx_target_text < 0 || idx_path < 0 )); then
    echo "Error: one or more required columns (ref_wav, ref_text, target_text, path) not found in $METADATA_TSV" >&2
    exit 1
fi

while IFS=$'\t' read -r -a cols; do
    ref_wav="${cols[$idx_ref_wav]}"
    ref_text="${cols[$idx_ref_text]}"
    target_text="${cols[$idx_target_text]}"
    path="${cols[$idx_path]}"

    # Check if output file already exists or is being generated by another process
    if [[ -f "$OUTPUT_DIR/$path" ]]; then
        echo "Output file already exists, skipping: $OUTPUT_DIR/$path"
        continue
    fi
    if [[ -f "$OUTPUT_DIR/$path.lock" ]]; then
        echo "Output file is being generated by another process, skipping: $OUTPUT_DIR/$path"
        continue
    fi
    # Create a lock file to indicate that this output file is being generated, and trap so that it is removed if the script is interrupted
    touch "$OUTPUT_DIR/$path.lock"
    trap "rm -f $OUTPUT_DIR/$path.lock; echo 'Cleaned up lock file'" EXIT
    # Pass to F5-TTS for inference
    f5-tts_infer-cli \
        --ref_audio "$ref_wav" \
        --ref_text "$ref_text" \
        --gen_text "$target_text" \
        --output_file "$path" \
        --device "$DEVICE" \
        --output_dir "$OUTPUT_DIR"
    # Remove the lock file after inference is complete
    rm "$OUTPUT_DIR/$path.lock"
done < <(tail -n +2 "$METADATA_TSV" | tr -d '\r')
echo "Inference complete for all possible samples in $METADATA_TSV"